name       : perl-set-intspan
version    : 1.19
release    : 6
source     :
    - http://search.cpan.org/CPAN/authors/id/S/SW/SWMCD/Set-IntSpan-1.19.tar.gz : 11b7549b13ec5d87cc695dd4c777cd02983dd5fe9866012877fb530f48b3dfd0
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Set::IntSpan - manage sets of integers
description: |
    Set::IntSpan - manage sets of integers
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
